export enum product  {
    READALLPOST='READALLPOST',
    CREATEPOST='CREATEPOST',
    READPOST='READPOST',
    UPDATEPOST='UPDATEPOST',
    DELETEPOST='DELETEPOST',
}
export enum brand  {
    READALLBRAND='READALLBRAND',
    CREATEBRAND='CREATEBRAND',
    READBRAND='READBRAND',
    UPDATEBRAND='UPDATEBRAND',
    DELETEBRAND='DELETEBRAND',
}
export enum categories  {
    READALLCATEGORY='READALLCATEGORY',
    CREATECATEGORY='CREATECATEGORY',
    READCATEGORY='READCATEGORY',
    UPDATECATEGORY='UPDATECATEGORY',
    DELETECATEGORY='DELETECATEGORY',
}
export enum color  {
    READALLCOLORS='READALLCOLORS',
}
export enum user  {
    SET='SET',
    SIGNIN='SIGNIN',
    SIGNUP='SIGNUP',
    LOGOUT='LOGOUT',
    AddCart = 'AddCart',
    REMOVEFROMCART='REMOVEFROMCART',
    REMOVEFROMCARTERR='REMOVEFROMCARTERR',
    READALLUSERS='READALLUSERS',
}