const express = require('express')
const upload = require('../lib/upload')
// const {getProduct,getProductList,createProduct,updateProduct,deleteProduct,getNewProduct,searchProduct,addRate,getProductbyCategory,getProducts} = require('../controller/product/index')
// const {CountProductList} = require('../controller/queries/count')
// const {DashBoard} = require('../controller/queries/dashboard')
// const {home} = require('../controller/queries/home')
// const {Status} = require('../controller/queries/status')
const {controller} = require('../controller')
const router = express.Router()
router.get('/',controller.product.getProductList)
router.get('/get/:id',controller.product.getProduct)
router.post('/',upload.array('images',12),controller.product.createProduct)
router.patch('/:id',controller.product.updateProduct)
router.delete('/:id',controller.product.deleteProduct)
// router.get('/count',CountProductList)
// router.get('/dashboard',DashBoard)
router.get('/new',controller.product.getNewProduct)
router.get('/search',controller.product.searchProduct)
router.post('/rate/:id',controller.product.addRate)
// router.get('/home',home)
router.get('/category',controller.product.getProductbyCategory)
router.get('/test',controller.product.getProducts)
// router.get('/status',Status)
module.exports = router